### PR TITLE
new visualise_dg_filter function added

### PR DESCRIPTION
**Pull request by michaelhennessyjr**

### CODE REVIEW

**Comment by PinkShnack** [comment]
In an expansion of this: we should maybe have magnitude sliders for both Gaussians. This would be best done with a cross-sectional view (the `fft.plot()` issue you had!) :). It is probably not too difficult to link both sets of sliders to two images, but let me know if it's hard.

We should definitely have a simple DGF function that only convolves the FFT and Gaussians and doesn't worry about managing the magnitudes. Then, we could add this as a third image in the plot, so when you click `filter`, the image is filtered before your very eyes. 

Thoughts?

**Comment by michaelhennessyjr** [comment]
Hey, thanks for checking it!

I'll make changes to have the example run properly (was wondering why pytest wasn't failing it..) and try to figure out why the filter button isn't working.

Is the apodization keyword still causing an error? If so I can just take it out, it's just used to give a clearer fft.

Magnitude sliders for the Gaussians would be useful for sure, as would having more than one DGF function. Those will take a while to implement so I'll try to get this version of the function working first and then can work on adding to it after!

**Comment by PinkShnack** [comment]
Hey @michaelhennessyjr  I'll be looking at this merge request again soon. I think what would be best at this point is to make the code work in it's most basic sense, then after add the cool extra stuff.

So I will try to:
* Make a function that just convolves two 2D signals and
* include that function in your class, so that when filter is clicked, the filtered signal is outputted.

**Comment by PinkShnack** [comment]
So I have added a few more basic DG filter functions for ease of use, and expanded the visualiser!

I also made a webpage for it. I think it is ready to merge whenever you like (as long as the tests pass!).

**Review by PinkShnack — APPROVED** [review]

**Pull request merged**
